fix(#23): add daily limit check
darwinia-network/wormhole-ui pull request #208
Opened 2021-11-30 11:51 UTC by sxlwar

## Priority

Do you need reviewers to review this PR as soon as possible?
- [x] Medium

## Help Merge

Do you need any other people to merge it if all checks passed and reviews were approved?

- [x] Yes - Merge it immediately

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix

## Does this PR introduce a breaking change?

- [x] No

## Why do we need this pr?

fix #23

2021-12-01 09:57 UTC, WoeOm requested changes

2021-12-01 09:57 UTC, WoeOm commented on src/components/records/D2ERecord.tsx
> +        isSufficient(arrival as EthereumConfig, 'ring'),
需要判断（该笔待领取 RING 的数量 是否大于 当日剩余额度）
比如：今日还剩 1 RING 额度，如果该笔跨链数量为 100 RING，应该不通过 isSufficient 检验

2021-12-02 02:50 UTC, WoeOm commented on src/components/records/D2ERecord.tsx
> +  return zip([limit, toadySpent]).pipe(map(([total, spent]) => new BN(total).sub(new BN(spent)).gte(amount)));
gt(amout) ？

2021-12-02 03:09 UTC, sxlwar commented on src/components/records/D2ERecord.tsx
> +  return zip([limit, toadySpent]).pipe(map(([total, spent]) => new BN(total).sub(new BN(spent)).gte(amount)));
相等应该允许领吧

2021-12-02 03:13 UTC, WoeOm commented on src/components/records/D2ERecord.tsx
> +  return zip([limit, toadySpent]).pipe(map(([total, spent]) => new BN(total).sub(new BN(spent)).gte(amount)));
是的。我看错了，以为方法是余额不足的判断

2021-12-02 03:14 UTC, WoeOm approved these changes

2021-12-02 03:15 UTC, merged